PERIPHERALS = pit
DRIVERS = pacer usb_serial adxl345
SRC = accelerometer.c LPF.c button_debounce.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = hat

include ../../boards/board.mk
