PERIPHERALS = pwm pit systick adc sam4s
DRIVERS = usb_serial pacer panic nrf24 led ledtape
SRC = main.c motors.c usb_commands.c radio.c darstadly_stuff.c led_racer.c low_voltage.c button_debounce.c # add dastardly stuff back in

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = racer

include ../../boards/board.mk